{
 "title": "Counter with Tags example",
 "tags": [
  "counter",
  "tags"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pie grouped by operation",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(prometheus_example_counter_tag_total) by (operation)"
    }
   ]
  },
  {
   "title": "Pie grouped by entity",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(prometheus_example_counter_tag_total) by (entity)"
    }
   ]
  },
  {
   "title": "Pie",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_example_counter_tag_total"
    }
   ]
  }
 ]
}